name: Pull request check

on: [pull_request]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
      
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_CORE }}
            ${{ secrets.SSH_PRIVATE_KEY_DS }}
      
      - name: "Bootstrap Workspace"
        run: flutter packages get && flutter packages get sample/
      - name: "Flutter Analyze"
        run: flutter analyze .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
      - name: "Flutter Format"
        run: flutter format . --set-exit-if-changed

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_CORE }}
            ${{ secrets.SSH_PRIVATE_KEY_DS }}
      - name: "Bootstrap Workspace"
        run: flutter packages get && flutter packages get sample/
      - name: "Flutter test"
        run: flutter test .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            